Repository overleaf/clsi, pull requests merged in 2020-06, with the labels that each got.

#169 record latexmk output
  app/js/LatexRunner.js
  app/js/ResourceWriter.js
  test/unit/js/LatexRunnerTests.js
  test/unit/js/ResourceWriterTests.js
Labels: Team-Ops, type:enhancement

#170 [DockerRunner] destroyOldContainers: fix a race confition
  app/js/DockerRunner.js
  test/unit/js/DockerRunnerTests.js
Labels: Team-Ops

#173 add setting TEXLIVE_OPENOUT_ANY
  app/js/CompileManager.js
  config/settings.defaults.js
Labels: Team-Ops, type:enhancement

#174 error on missing profile
  config/settings.defaults.js
Labels: Team-Ops

#177 add missing setting for optimiseInDocker
  config/settings.defaults.js
Labels: Team-Ops, type:bug

#175 send 503 unavailable response on EPIPE
  app.js
Labels: Team-Ops

#176 Remove Retries in EPIPE Errors
  app/js/DockerRunner.js
  test/unit/js/DockerRunnerTests.js
Labels: Team-Aqua, type:bug

#178 migrate from underscore to lodash
  app/js/DockerRunner.js
  app/js/OutputCacheManager.js
  app/js/OutputFileOptimiser.js
  app/js/db.js
  package-lock.json
  package.json
  test/load/js/loadTest.js
  test/unit/js/DockerRunnerTests.js
  test/unit/js/OutputFileOptimiserTests.js
Labels: Team-Ops

#179 fix synctex error
  app.js
  app/js/CompileManager.js
  test/acceptance/js/SynctexTests.js
  test/acceptance/js/helpers/Client.js
Labels: Team-Ops, type:bug

#180 add compile groups support
  app/js/CompileManager.js
  app/js/DockerRunner.js
  app/js/LatexRunner.js
  app/js/LocalCommandRunner.js
  app/js/RequestParser.js
  config/settings.defaults.js
  test/unit/js/CompileManagerTests.js
  test/unit/js/DockerRunnerTests.js
  test/unit/js/LatexRunnerTests.js
Labels: Team-Ops, type:enhancement

#181 handle EPIPE errors in CompileController
  app/js/CompileController.js
Labels: Team-Ops, type:bug
