Repository overleaf/clsi, pull requests merged in 2020-05, with the labels that each got.

#168 add refreshExpiryTimeout function
  app.js
  app/js/ProjectPersistenceManager.js
  package-lock.json
  package.json
  test/unit/js/ProjectPersistenceManagerTests.js
Labels: Team-Ops

#163 set encoding when reading from streams
  app/js/CompileManager.js
  app/js/LocalCommandRunner.js
  app/js/OutputFileFinder.js
  app/js/OutputFileOptimiser.js
  test/unit/js/CompileManagerTests.js
  test/unit/js/OutputFileFinderTests.js
Labels: type:bug

#164 fix deprecated usage of Buffer constructor
  app/js/OutputFileOptimiser.js
  app/js/SafeReader.js
  test/unit/js/OutputFileOptimiserTests.js
Labels: type:bug

#166 [misc] simplify the smoke test and process shutdown
  app.js
  package-lock.json
  package.json
  test/smoke/js/SmokeTests.js
Labels: Team-Ops

#162 [DockerRunner] retry container inspect on EPIPE
  app/js/DockerRunner.js
  test/unit/js/DockerRunnerTests.js
Labels: Team-Magma, Team-Ops
