Repository overleaf/clsi, pull requests merged in 2021-01, with the labels that each got.

#203 [misc] bump the node version to 10.23.1
  .nvmrc
  Dockerfile
  buildscript.txt
Labels: Team-Magma, Team-Ops

#202 [misc] CompileController: exact match for output.pdf
  app/js/CompileController.js
  test/unit/js/CompileControllerTests.js
Labels: Team-Magma, type:bug

#200 decaff cleanup ResourceStateManager
  app/js/ResourceStateManager.js
Labels: Team-Ops

#201 decaff cleanup of OutputFileManager
  app/js/OutputFileFinder.js
  test/unit/js/OutputFileFinderTests.js
Labels: Team-Ops

#204 use separate output dir for generated files
  .gitignore
  Dockerfile
  app.js
  app/js/CompileManager.js
  app/js/OutputCacheManager.js
  config/settings.defaults.js
  test/unit/js/CompileManagerTests.js
Labels: Team-Ops, type:enhancement
