Repository overleaf/clsi, pull requests merged in 2021-05, with the labels that each got.

#225 [misc] add metrics for pdf caching and dark mode for compute only
  app/js/CompileController.js
  app/js/CompileManager.js
  app/js/ContentCacheManager.js
  app/js/ContentCacheMetrics.js
  app/js/OutputCacheManager.js
  config/settings.defaults.js
  docker-compose.ci.yml
  docker-compose.yml
  test/acceptance/js/Stats.js
  test/acceptance/js/helpers/Client.js
  test/unit/js/CompileControllerTests.js
  test/unit/js/CompileManagerTests.js
Labels: Team-Magma

#227 [misc] add a config option for the min chunk size of pdf ranges
  app/js/ContentCacheManager.js
  config/settings.defaults.js
Labels: Team-Magma

#226 [misc] merge pdf caching into main
  app.js
  app/js/CompileController.js
  app/js/CompileManager.js
  app/js/ContentCacheManager.js
  app/js/ContentCacheMetrics.js
  app/js/ContentController.js
  app/js/OutputCacheManager.js
  app/js/RequestParser.js
  config/settings.defaults.js
  docker-compose.ci.yml
  docker-compose.yml
  test/acceptance/js/Stats.js
  test/acceptance/js/helpers/Client.js
  test/unit/js/CompileControllerTests.js
  test/unit/js/CompileManagerTests.js
Labels: Team-Magma

#224 add hash benchmark script
  test/bench/hashbench.js
Labels: Team-Magma

#228 add validation for express content routes
  app.js
  app/js/ContentCacheManager.js
  app/js/OutputCacheManager.js
Labels: Team-Magma

#231 use fs.copyFile for performance
  app/js/UrlCache.js
  test/unit/js/UrlCacheTests.js
Labels: Team-Magma

#232 upgrade fs-extra
  package-lock.json
  package.json
Labels: Team-Magma, dependencies

#233 [perf] drop useless synchronous syscall on hot path for writing docs
  app/js/ResourceWriter.js
Labels: Team-Magma, type:bug

#234 [ContentCacheManager] add support for stream detection across chunks
  app/js/ContentCacheManager.js
  test/unit/js/ContentCacheManagerTests.js
Labels: Team-Magma, type:bug

#235 [ContentCacheManager] write streams to disk atomically
  app/js/ContentCacheManager.js
Labels: Team-Magma

#236 [ContentCacheManager] skip writing of duplicate streams
  app/js/ContentCacheManager.js
Labels: Team-Magma

#237 [misc] fix unit tests following the merge of atomic writes
  test/unit/js/ContentCacheManagerTests.js
Labels: Team-Magma, type:bug

#238 [LatexRunner] do not emit empty cpu/sys timings
  app/js/LatexRunner.js
  test/unit/js/LatexRunnerTests.js
Labels: Team-Magma, type:bug

#240 [ContentCacheManager] track hashes and expire unused ones
  app/js/ContentCacheManager.js
  app/js/ContentCacheMetrics.js
  app/js/OutputCacheManager.js
  package-lock.json
  package.json
  test/unit/js/ContentCacheManagerTests.js
Labels: Team-Magma

#241 [misc] AllowedImageNamesTests: add missing done callbacks
  test/acceptance/js/AllowedImageNamesTests.js
Labels: type:bug

#242 [ContentCacheManager] use PDF.js Xref table instead of stream detection
  app/js/ContentCacheManager.js
  app/js/OutputCacheManager.js
  app/lib/pdfjs/FSPdfManager.js
  app/lib/pdfjs/FSStream.js
  app/lib/pdfjs/parseXrefTable.js
  package-lock.json
  package.json
  scripts/demo-pdfjs-Xref.js
  test/acceptance/fixtures/minimal.pdf
  test/unit/js/ContentCacheManagerTests.js
  test/unit/js/snapshots/minimalCompile/chunks/896749b8343851b0dc385f71616916a7ba0434fcfb56d1fc7e27cd139eaa2f71
  test/unit/js/snapshots/minimalCompile/chunks/d7cfc73ad2fba4578a437517923e3714927bbf35e63ea88bd93c7a8076cf1fcd
  test/unit/lib/pdfjsTests.js
  test/unit/lib/snapshots/asymptote/XrefTable.json
  test/unit/lib/snapshots/biber_bibliography/XrefTable.json
  test/unit/lib/snapshots/epstopdf/XrefTable.json
  test/unit/lib/snapshots/feynmf/XrefTable.json
  test/unit/lib/snapshots/feynmp/XrefTable.json
  test/unit/lib/snapshots/fontawesome/XrefTable.json
  test/unit/lib/snapshots/fontawesome_xelatex/XrefTable.json
  test/unit/lib/snapshots/glossaries/XrefTable.json
  test/unit/lib/snapshots/gnuplot/XrefTable.json
  test/unit/lib/snapshots/hebrew/XrefTable.json
  test/unit/lib/snapshots/knitr/XrefTable.json
  test/unit/lib/snapshots/knitr_utf8/XrefTable.json
  test/unit/lib/snapshots/latex_compiler/XrefTable.json
  test/unit/lib/snapshots/lualatex_compiler/XrefTable.json
  test/unit/lib/snapshots/makeindex-custom-style/XrefTable.json
  test/unit/lib/snapshots/makeindex/XrefTable.json
  test/unit/lib/snapshots/minted/XrefTable.json
  test/unit/lib/snapshots/multibib_bibliography/XrefTable.json
  test/unit/lib/snapshots/nomenclature/XrefTable.json
  test/unit/lib/snapshots/references_in_include/XrefTable.json
  test/unit/lib/snapshots/simple_bibliography/XrefTable.json
  test/unit/lib/snapshots/subdirectories/XrefTable.json
  test/unit/lib/snapshots/tikz_feynman/XrefTable.json
  test/unit/lib/snapshots/xelatex_compiler/XrefTable.json
Labels: Team-Magma
