Repository overleaf/clsi, pull requests merged in 2021-03, with the labels that each got.

#214 Upgrade to Node 12
  .dockerignore
  .mocharc.json
  .nvmrc
  Dockerfile
  Makefile
  buildscript.txt
  test/acceptance/js/BrokenLatexFileTests.js
  test/acceptance/js/DeleteOldFilesTest.js
  test/acceptance/js/ExampleDocumentTests.js
  test/acceptance/js/SimpleLatexFileTests.js
  test/acceptance/js/SynctexTests.js
  test/acceptance/js/TimeoutTests.js
  test/acceptance/js/UrlCachingTests.js
  test/acceptance/js/WordcountTests.js
  test/setup.js
  test/unit/js/CompileControllerTests.js
  test/unit/js/CompileManagerTests.js
  test/unit/js/ContentTypeMapperTests.js
  test/unit/js/DockerLockManagerTests.js
  test/unit/js/DockerRunnerTests.js
  test/unit/js/DraftModeManagerTests.js
  test/unit/js/LatexRunnerTests.js
  test/unit/js/LockManagerTests.js
  test/unit/js/OutputFileFinderTests.js
  test/unit/js/OutputFileOptimiserTests.js
  test/unit/js/ProjectPersistenceManagerTests.js
  test/unit/js/RequestParserTests.js
  test/unit/js/ResourceStateManagerTests.js
  test/unit/js/ResourceWriterTests.js
  test/unit/js/StaticServerForbidSymlinksTests.js
  test/unit/js/TikzManager.js
  test/unit/js/UrlCacheTests.js
  test/unit/js/UrlFetcherTests.js
Labels: Team-Magma

#216 Add missing environment variables to CLSI README.
  README.md
Labels: Team-Ops

#210 [misc] bump the version of the metrics module to 3.5.1
  package-lock.json
  package.json
Labels: Team-Magma

#215 support post and get for getting status of clsi project
  app.js
Labels: Team-Magma

#213 Update README
  README.md
Labels: Team-Aqua

#212 Ensure that app folders exist before running chown in entrypoint.sh
  entrypoint.sh
Labels: Team-Aqua

#217 Add flag to qpdf, to preserve PDF/A compliance
  app/js/OutputFileOptimiser.js
Labels: Team-Magma

#218 [misc] bump the version of the metrics module to 3.5.1
  package-lock.json
  package.json
Labels: Team-Magma, dependencies

#219 [misc] consume and validate a custom imageName for synctex requests
  app/js/CompileController.js
  app/js/CompileManager.js
  test/acceptance/js/AllowedImageNames.js
  test/acceptance/js/SynctexTests.js
  test/acceptance/js/helpers/Client.js
  test/unit/js/CompileControllerTests.js
  test/unit/js/CompileManagerTests.js
Labels: Team-Magma
